$ErrorActionPreference = 'Stop'
$scriptPath = Join-Path $PSScriptRoot '../PSFzf.psm1'
Set-Content -Path $scriptPath -Value ('# AUTOGENERATED - DO NOT EDIT' + "`n")

# All your Base are belong to us (contains param block that must be first)
$basePath = Join-Path $PSScriptRoot '../PSFzf.Base.ps1'
if (Test-Path $basePath) {
    Write-Host "Adding PSFzf.Base.ps1"
    Add-Content -Path $scriptPath -Value "# PSFzf.Base.ps1"
    Get-Content -Path $basePath | Add-Content -Path $scriptPath
}

# For great justice, take off every 'zig' (add all other PSFzf.*.ps1 files)
Get-ChildItem (Join-Path $PSScriptRoot '../PSFzf.*.ps1') |
Where-Object { $_.Name -ne 'PSFzf.Base.ps1' -and $_.Name -ne 'PSFzf.tests.ps1' } |
ForEach-Object {
    $name = $_.Name
    Write-Host "Adding $name"
    Add-Content -Path $scriptPath -Value "# $name"
    Get-Content -Path $_ | Add-Content -Path $scriptPath
}

$scriptPath = Resolve-Path $scriptPath
Write-Host "Created $scriptPath"